### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by tschorr** [plone/Products.isurlinportal#2]
This package seems to work fine with Python 3.8. Is there a reason why Python 3.8 is not included in test matrix + classifiers list? Also, I have tried to create a PR for this, but I'm not allowed to push (although I'm member of plone). Maybe a permissions issue?

**Comment by mauritsvanrees** [comment]
It is not included because in my mind Plone 5.2 only supports Python 3.7 as highest version. That may be because Jenkins pull request jobs are always run for Python 2.7, 3.6 and 3.7. Python 3.8 *is* tested on Jenkins though. But I am not even sure if we officially support 3.8, and I am one of the release managers...

Anyway, should be fine to include it here.

When I go to Settings / Manage Access, I see options that I have not seen yet. Maybe this is the default for new projects.

On the organisational level we may need to give plone Members a base role of Write, at https://github.com/organizations/plone/settings/member_privileges

But for now I gave `plone/developers` write access to this repository.

![Screenshot 2020-08-18 at 12 06 01](https://user-images.githubusercontent.com/210587/90500560-5995ae80-e14b-11ea-91a1-17d49edc1153.png)

**Comment by mauritsvanrees** [comment]
This setting is the default in a few other plone repositories I checked. Maybe we always do this by hand, I just don't remember ever doing it. Oh well, you should be able to make a PR now.

**Comment by tschorr** [comment]
> Oh well, you should be able to make a PR now.

Yes, I can push now.

> But I am not even sure if we officially support 3.8, and I am one of the release managers...

I was confused because I'm using Plone with Python 3.8 since a while. So I searched and found this [PLIP](https://github.com/plone/Products.CMFPlone/issues/2890). It's still open, but the only missing tick in the deliverables section is "Update documentation". So imho new packages should be tested + classified for Python 3.8.
